// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SayGoClient is the client API for SayGo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SayGoClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type sayGoClient struct {
	cc grpc.ClientConnInterface
}

func NewSayGoClient(cc grpc.ClientConnInterface) SayGoClient {
	return &sayGoClient{cc}
}

func (c *sayGoClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/wei.hello.SayGo/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sayGoClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/wei.hello.SayGo/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayGoServer is the server API for SayGo service.
// All implementations must embed UnimplementedSayGoServer
// for forward compatibility
type SayGoServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedSayGoServer()
}

// UnimplementedSayGoServer must be embedded to have forward compatible implementations.
type UnimplementedSayGoServer struct {
}

func (UnimplementedSayGoServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedSayGoServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedSayGoServer) mustEmbedUnimplementedSayGoServer() {}

// UnsafeSayGoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SayGoServer will
// result in compilation errors.
type UnsafeSayGoServer interface {
	mustEmbedUnimplementedSayGoServer()
}

func RegisterSayGoServer(s grpc.ServiceRegistrar, srv SayGoServer) {
	s.RegisterService(&SayGo_ServiceDesc, srv)
}

func _SayGo_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayGoServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wei.hello.SayGo/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayGoServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SayGo_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayGoServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wei.hello.SayGo/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayGoServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SayGo_ServiceDesc is the grpc.ServiceDesc for SayGo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SayGo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wei.hello.SayGo",
	HandlerType: (*SayGoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _SayGo_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _SayGo_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SayGo.proto",
}
